[core]
reloadable = true
[package]
version = "0.1.0"
title = "G1 live sensor publisher"
[dependencies]
"isaacsim.core.api" = {}
"isaacsim.sensors.physics" = {}
[[python.module]]
name = "isaacsim.g1.livesensor"
