FROM pipeline-base

SHELL ["/bin/bash", "-c"]

WORKDIR /root/pipeline_ws

COPY src/ src/

RUN source /opt/ros/humble/setup.bash && \
    rosdep install --from-paths src --ignore-src -r -y && \
    colcon build --symlink-install && \
    rm -rf build/ log/

RUN echo "source /root/pipeline_ws/install/setup.bash" >> /root/.bashrc

COPY docker/entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/bin/bash"]
